In [3]:
from googleapiclient.discovery import build
from IPython.display import display
from langdetect import detect, DetectorFactory
from tqdm import tqdm
import pandas as pd
import isodate
import emoji
import re
import time
import datetime

DetectorFactory.seed = 0
print("[SUCCESS] All Libraries Imported.")

[SUCCESS] All Libraries Imported.

In [6]:
# ==============================================================
# STEP 1: API KEY & GLOBAL CONFIGURATION
# ==============================================================
print("=== YouTube Virality Study | GROUP 05 ===")
print("Get your API Key from: https://console.cloud.google.com/\n")

API_KEY            = "AIzaSyD05oVTSL-5TjfGdZLXQdFb4J--rzHJEzw"
VIDEOS_PER_CHANNEL = 40
VAULT_FILE         = 'yt_video_vault.csv'
TODAY              = datetime.datetime.utcnow().date()
youtube            = build('youtube', 'v3', developerKey=API_KEY)

print(f"\n[SUCCESS] YouTube API Client Ready.")
print(f"Videos Per Channel : {VIDEOS_PER_CHANNEL}")
print(f"Total Target       : {VIDEOS_PER_CHANNEL * 2} videos")
print(f"Today (UTC)        : {TODAY}")
print(f"Output File        : {VAULT_FILE}")
print("-" * 60)

=== YouTube Virality Study | GROUP 05 ===
Get your API Key from: https://console.cloud.google.com/


[SUCCESS] YouTube API Client Ready.
Videos Per Channel : 40
Total Target       : 80 videos
Today (UTC)        : 2026-03-13
Output File        : yt_video_vault.csv
------------------------------------------------------------

C:\Users\91828\AppData\Local\Temp\ipykernel_14296\872726046.py:10: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  TODAY              = datetime.datetime.utcnow().date()

In [7]:
# ==============================================================
# STEP 2: DEFINE TARGET CHANNELS
# ==============================================================

print("=== CHANNEL SETUP ===\n")

channel_targets = {
    'Slayy Point': {
        'channel_id'    : 'UCtgGOdTlM-NdJ9rPKIYN8UQ',
        'category'      : 'Roast',
        'category_code' : 0
    },
    'Passenger Paramvir': {
        'channel_id'    : 'UCK2_PiPOB0VEZfbbaHj-z5w',
        'category'      : 'Travel Vlog',
        'category_code' : 1
    }
}

print("[SUCCESS] Channels Configured:")
for name, info in channel_targets.items():
    print(f"  {name}")
    print(f"    Channel ID : {info['channel_id']}")
    print(f"    Category   : {info['category']} (Code = {info['category_code']})")
print("-" * 60)

=== CHANNEL SETUP ===

[SUCCESS] Channels Configured:
  Slayy Point
    Channel ID : UCtgGOdTlM-NdJ9rPKIYN8UQ
    Category   : Roast (Code = 0)
  Passenger Paramvir
    Channel ID : UCK2_PiPOB0VEZfbbaHj-z5w
    Category   : Travel Vlog (Code = 1)
------------------------------------------------------------

In [8]:
# ==============================================================
# STEP 3: HELPER FUNCTIONS
# ==============================================================

# Power words list exactly as defined in your document (Table 5)
POWER_WORDS = [
    'exposed', 'roasted', 'shocked', 'viral', 'worst', 'best',
    'brutal', 'secret', 'insane', 'truth', 'never', 'destroyed'
]

def get_sensationalism_score(title):
    score       = 0
    title_lower = title.lower()
    # 1. Power words — +1 per match
    score += sum(1 for word in POWER_WORDS if word in title_lower)
    # 2. ALL CAPS words — skip single letters
    score += sum(1 for word in title.split() if word.isupper() and len(word) > 1)
    # 3. Numbers — regex \d+
    score += len(re.findall(r'\d+', title))
    # 4. Emojis
    score += emoji.emoji_count(title)
    # 5. ! and ? marks
    score += title.count('!') + title.count('?')
    return score

def get_language(text):
    try:
        return detect(str(text))
    except:
        return 'unknown'

print("[SUCCESS] Helper Functions Ready.")
print("  -> get_sensationalism_score() : IDV2")
print("  -> get_language()             : C4")

[SUCCESS] Helper Functions Ready.
  -> get_sensationalism_score() : IDV2
  -> get_language()             : C4

In [9]:
# ==============================================================
# STEP 4: CORE SCRAPING FUNCTIONS
# ==============================================================

def get_subscriber_count(channel_id):
    try:
        response = youtube.channels().list(
            part='statistics', id=channel_id
        ).execute()
        return int(response['items'][0]['statistics'].get('subscriberCount', 0))
    except Exception as e:
        print(f"      [!] Subscriber count error: {e}")
        return 0


def get_uploads_playlist_id(channel_id):
    # Every channel has a hidden 'uploads' playlist
    # This is the most reliable way to get exactly N videos
    try:
        response = youtube.channels().list(
            part='contentDetails', id=channel_id
        ).execute()
        return response['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    except Exception as e:
        print(f"      [!] Uploads playlist error: {e}")
        return None


def get_video_ids(channel_id, max_videos=40):
    video_ids       = []
    next_page_token = None

    playlist_id = get_uploads_playlist_id(channel_id)
    if not playlist_id:
        print("      [!] Could not get uploads playlist. Skipping.")
        return []

    print(f"     Uploads Playlist ID : {playlist_id}")

    # Paginate until we have exactly max_videos IDs
    while len(video_ids) < max_videos:
        remaining = max_videos - len(video_ids)
        try:
            response = youtube.playlistItems().list(
                part       = 'contentDetails',
                playlistId = playlist_id,
                maxResults = min(50, remaining),
                pageToken  = next_page_token
            ).execute()

            for item in response.get('items', []):
                video_ids.append(item['contentDetails']['videoId'])
                if len(video_ids) >= max_videos:
                    break

            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break

            time.sleep(0.3)

        except Exception as e:
            print(f"      [!] Playlist pagination error: {e}")
            break

    print(f"     Video IDs Collected : {len(video_ids)} / {max_videos}")
    return video_ids


def get_video_details(video_ids):
    # YouTube API allows max 50 IDs per call — 40 videos = 1 batch
    all_details = []
    for i in range(0, len(video_ids), 50):
        batch = video_ids[i:i+50]
        try:
            response = youtube.videos().list(
                part='snippet,statistics,contentDetails',
                id  =','.join(batch)
            ).execute()
            all_details.extend(response.get('items', []))
            time.sleep(0.5)
        except Exception as e:
            print(f"      [!] Video details error: {e}")
    return all_details


print("[SUCCESS] Scraping Functions Ready.")
print("  -> get_subscriber_count()     : C1")
print("  -> get_uploads_playlist_id()  : Gets hidden uploads playlist")
print("  -> get_video_ids()            : Fetches EXACTLY 40 video IDs")
print("  -> get_video_details()        : Fetches full metadata")

[SUCCESS] Scraping Functions Ready.
  -> get_subscriber_count()     : C1
  -> get_uploads_playlist_id()  : Gets hidden uploads playlist
  -> get_video_ids()            : Fetches EXACTLY 40 video IDs
  -> get_video_details()        : Fetches full metadata

In [10]:
# ==============================================================
# PHASE 1: MAIN EXTRACTION — 80 VIDEOS TOTAL
# ==============================================================

print(f"\n=== PHASE 1: EXTRACTION ===")
print(f"Target : {VIDEOS_PER_CHANNEL} videos × {len(channel_targets)} channels = {VIDEOS_PER_CHANNEL * 2} total\n")

all_video_data = []

for channel_name, channel_info in channel_targets.items():

    channel_id    = channel_info['channel_id']
    category      = channel_info['category']
    category_code = channel_info['category_code']

    print(f"[+] Channel  : {channel_name}  |  Category : {category}")
    print("-" * 60)

    # Step A: Subscriber Count — C1
    print("  -> Step A: Subscriber Count...")
    subscriber_count = get_subscriber_count(channel_id)
    print(f"     Subscribers : {subscriber_count:,}")

    # Step B: Get exactly 40 Video IDs
    print(f"\n  -> Step B: Fetching {VIDEOS_PER_CHANNEL} Video IDs...")
    video_ids = get_video_ids(channel_id, max_videos=VIDEOS_PER_CHANNEL)
    if not video_ids:
        print(f"     [!] No videos found. Skipping.")
        continue

    # Step C: Full metadata for all 40 videos
    print(f"\n  -> Step C: Fetching Video Metadata...")
    video_details = get_video_details(video_ids)
    print(f"     Retrieved : {len(video_details)} videos")

    # Step D: Parse fields and compute all variables
    print(f"\n  -> Step D: Computing Variables...")

    for video in tqdm(video_details, desc=f"     {channel_name}"):
        try:
            snippet    = video.get('snippet', {})
            statistics = video.get('statistics', {})
            content    = video.get('contentDetails', {})

            # ----------------------------------------
            # RAW FIELDS — directly from API
            # ----------------------------------------
            video_id      = video.get('id', '')
            title         = snippet.get('title', '')
            tags          = snippet.get('tags', [])
            published_at  = snippet.get('publishedAt', '')

            views         = int(statistics.get('viewCount',    0))
            likes         = int(statistics.get('likeCount',    0))
            comment_count = int(statistics.get('commentCount', 0))

            # Duration: ISO 8601 → seconds → minutes
            duration_iso  = content.get('duration', 'PT0S')
            duration_secs = int(isodate.parse_duration(duration_iso).total_seconds())
            duration_mins = round(duration_secs / 60, 2)

            # Dates
            upload_dt       = pd.to_datetime(published_at)
            upload_date     = upload_dt.date()
            video_age_days  = (TODAY - upload_date).days
            day_of_week     = upload_dt.day_name()
            day_of_week_num = upload_dt.weekday()    # 0=Mon, 6=Sun

            # ----------------------------------------
            # DEPENDENT VARIABLE
            # ----------------------------------------
            dv_virality_score = round(views / subscriber_count, 6) if subscriber_count > 0 else 0

            # ----------------------------------------
            # INDEPENDENT VARIABLES
            # ----------------------------------------
            idv1_engagement_rate      = round((likes + comment_count) / views * 100, 4) if views > 0 else 0
            idv2_title_sensationalism = get_sensationalism_score(title)
            idv3_duration_minutes     = duration_mins
            idv4a_comment_volume      = comment_count   # Part B (positive ratio) → added in Part 2
            idv5_tag_count            = len(tags)
            idv6_title_length         = len(title.split())
            # idv7_reply_eng_rate     → added in Part 2 (needs comment scraping)

            # ----------------------------------------
            # MEDIATOR 1
            # ----------------------------------------
            med1_like_to_view_ratio   = round(likes / views * 100, 4) if views > 0 else 0
            # med2_comment_sentiment  → added in Part 2

            # ----------------------------------------
            # MODERATORS
            # ----------------------------------------
            mod1_content_category    = category
            mod1_category_code       = category_code
            mod2_upload_recency_days = video_age_days

            # ----------------------------------------
            # CONTROL VARIABLES
            # ----------------------------------------
            cv4_language = get_language(title)

            # ----------------------------------------
            # FINAL RECORD — 1 row per video
            # ----------------------------------------
            record = {
                # Identifiers
                'channel_name'              : channel_name,
                'video_id'                  : video_id,
                'video_url'                 : f"https://www.youtube.com/watch?v={video_id}",
                'title'                     : title,
                # Raw counts
                'views'                     : views,
                'likes'                     : likes,
                'raw_comment_count'         : comment_count,
                'raw_duration_seconds'      : duration_secs,
                'raw_tag_count'             : len(tags),
                'raw_upload_date'           : upload_date,
                'raw_published_at'          : published_at,
                # DV
                'dv_virality_score'         : dv_virality_score,
                # IDVs
                'idv1_engagement_rate'      : idv1_engagement_rate,
                'idv2_title_sensationalism' : idv2_title_sensationalism,
                'idv3_duration_minutes'     : idv3_duration_minutes,
                'idv4a_comment_volume'      : idv4a_comment_volume,
                'idv5_tag_count'            : idv5_tag_count,
                'idv6_title_length'         : idv6_title_length,
                # idv4b and idv7 filled in Part 2
                # Mediators
                'med1_like_to_view_ratio'   : med1_like_to_view_ratio,
                # med2 filled in Part 2
                # Moderators
                'mod1_content_category'     : mod1_content_category,
                'mod1_category_code'        : mod1_category_code,
                'mod2_upload_recency_days'  : mod2_upload_recency_days,
                # Control Variables
                'cv1_subscriber_count'      : subscriber_count,
                'cv2_video_age_days'        : video_age_days,
                'cv3_day_of_week'           : day_of_week,
                'cv3_day_of_week_num'       : day_of_week_num,
                'cv4_language'              : cv4_language,
            }

            all_video_data.append(record)

        except Exception as e:
            print(f"\n      [!] Error on video '{video.get('id','?')}': {e}")
            continue

    ch_done = len([r for r in all_video_data if r['channel_name'] == channel_name])
    print(f"\n  [SUCCESS] {channel_name} : {ch_done} videos processed.")
    print("=" * 60 + "\n")

# Save vault
if len(all_video_data) > 0:
    df = pd.DataFrame(all_video_data)
    df.to_csv(VAULT_FILE, index=False)
    print(f"[DONE] Vault Saved     : {VAULT_FILE}")
    print(f"Total Rows             : {len(df)}")
    print(f"Total Columns          : {len(df.columns)}")
    for name in channel_targets:
        print(f"  {name:35s} : {len(df[df['channel_name']==name])} videos")
else:
    print("FATAL ERROR: No data scraped. Check API Key and Channel IDs.")

=== PHASE 1: EXTRACTION ===
Target : 40 videos × 2 channels = 80 total

[+] Channel  : Slayy Point  |  Category : Roast
------------------------------------------------------------
  -> Step A: Subscriber Count...
     Subscribers : 10,400,000

  -> Step B: Fetching 40 Video IDs...
     Uploads Playlist ID : UUtgGOdTlM-NdJ9rPKIYN8UQ
     Video IDs Collected : 40 / 40

  -> Step C: Fetching Video Metadata...
     Retrieved : 40 videos

  -> Step D: Computing Variables...

     Slayy Point: 100%|██████████| 40/40 [00:00<00:00, 46.90it/s]

  [SUCCESS] Slayy Point : 40 videos processed.
============================================================

[+] Channel  : Passenger Paramvir  |  Category : Travel Vlog
------------------------------------------------------------
  -> Step A: Subscriber Count...
     Subscribers : 2,640,000

  -> Step B: Fetching 40 Video IDs...
     Uploads Playlist ID : UUK2_PiPOB0VEZfbbaHj-z5w
     Video IDs Collected : 40 / 40

  -> Step C: Fetching Video Metadata...
     Retrieved : 40 videos

  -> Step D: Computing Variables...

     Passenger Paramvir: 100%|██████████| 40/40 [00:00<00:00, 117.95it/s]

  [SUCCESS] Passenger Paramvir : 40 videos processed.
============================================================

[DONE] Vault Saved     : yt_video_vault.csv
Total Rows             : 80
Total Columns          : 27
  Slayy Point                         : 40 videos
  Passenger Paramvir                  : 40 videos

In [11]:
# ==============================================================
# PHASE 2: VAULT PREVIEW
# ==============================================================

df = pd.read_csv(VAULT_FILE)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 40)

print(f"Rows : {len(df)}  |  Columns : {len(df.columns)}\n")
for i, col in enumerate(df.columns, 1):
    print(f"  {i:02d}. {col}")

print("\n--- FIRST 5 RECORDS ---")
display(df.head(5))

Rows : 80  |  Columns : 27

  01. channel_name
  02. video_id
  03. video_url
  04. title
  05. views
  06. likes
  07. raw_comment_count
  08. raw_duration_seconds
  09. raw_tag_count
  10. raw_upload_date
  11. raw_published_at
  12. dv_virality_score
  13. idv1_engagement_rate
  14. idv2_title_sensationalism
  15. idv3_duration_minutes
  16. idv4a_comment_volume
  17. idv5_tag_count
  18. idv6_title_length
  19. med1_like_to_view_ratio
  20. mod1_content_category
  21. mod1_category_code
  22. mod2_upload_recency_days
  23. cv1_subscriber_count
  24. cv2_video_age_days
  25. cv3_day_of_week
  26. cv3_day_of_week_num
  27. cv4_language

--- FIRST 5 RECORDS ---

,channel_name,video_id,video_url,title,views,likes,raw_comment_count,raw_duration_seconds,raw_tag_count,raw_upload_date,raw_published_at,dv_virality_score,idv1_engagement_rate,idv2_title_sensationalism,idv3_duration_minutes,idv4a_comment_volume,idv5_tag_count,idv6_title_length,med1_like_to_view_ratio,mod1_content_category,mod1_category_code,mod2_upload_recency_days,cv1_subscriber_count,cv2_video_age_days,cv3_day_of_week,cv3_day_of_week_num,cv4_language
0,Slayy Point,ruJlB_T-zBk,https://www.youtube.com/watch?v=ruJl...,Trying DOSAs That Rich People Eat (E...,1335552,94398,5317,937,7,2026-03-12,2026-03-12T14:32:35Z,0.128418,7.4662,1,15.62,5317,7,7,7.0681,Roast,0,1,10400000,1,Thursday,3,en
1,Slayy Point,FJL-N0srAVU,https://www.youtube.com/watch?v=FJL-...,I Found WORST Named Restaurants On D...,6440758,212565,7387,1056,8,2026-01-29,2026-01-29T14:14:34Z,0.619304,3.4150,2,17.60,7387,8,8,3.3003,Roast,0,43,10400000,43,Thursday,3,en
2,Slayy Point,tZ_k-SfcENc,https://www.youtube.com/watch?v=tZ_k...,Checking If Ghosts Exist in India's ...,8042686,267332,9020,1499,9,2026-01-06,2026-01-06T13:48:09Z,0.773335,3.4361,0,24.98,9020,9,8,3.3239,Roast,0,66,10400000,66,Tuesday,1,en
3,Slayy Point,tBPPEmexsBs,https://www.youtube.com/watch?v=tBPP...,Rich Weddings vs YouTuber Wedding | ...,8588128,266287,5695,1052,6,2025-12-16,2025-12-16T12:46:25Z,0.825782,3.1670,0,17.53,5695,6,7,3.1006,Roast,0,87,10400000,87,Tuesday,1,en
4,Slayy Point,3rfErh6jqlg,https://www.youtube.com/watch?v=3rfE...,Meeting India's Biggest YouTubers To...,10797277,487800,15672,1099,21,2025-11-14,2025-11-14T13:04:18Z,1.038200,4.6630,2,18.32,15672,21,9,4.5178,Roast,0,119,10400000,119,Friday,4,en

In [12]:
# ==============================================================
# PHASE 3: SUMMARY STATISTICS
# ==============================================================

df = pd.read_csv(VAULT_FILE)

numeric_cols = [
    'dv_virality_score', 'idv1_engagement_rate', 'idv2_title_sensationalism',
    'idv3_duration_minutes', 'idv4a_comment_volume', 'idv5_tag_count',
    'idv6_title_length', 'med1_like_to_view_ratio', 'mod2_upload_recency_days',
    'cv1_subscriber_count', 'cv2_video_age_days', 'views', 'likes'
]

print("--- MEAN VALUES PER CHANNEL ---")
display(df.groupby('channel_name')[numeric_cols].mean().round(3).T)

print("\n--- VIRALITY SCORE BREAKDOWN ---")
display(df.groupby('channel_name')['dv_virality_score'].agg(
    Mean='mean', Median='median', Max='max', Min='min', Std='std'
).round(6))

print("\n--- LANGUAGE DISTRIBUTION ---")
display(df.groupby(['channel_name','cv4_language']).size().unstack(fill_value=0))

print("\n--- MISSING VALUES ---")
missing = df[numeric_cols].isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else "No missing values.")

print("\n[DONE] Part 1 Complete.")
print("[NEXT] Run Part 2 to scrape 20 comments per video.")
print("       Part 2 adds: idv4b_positive_ratio, idv7_reply_rate, med2_sentiment")

--- MEAN VALUES PER CHANNEL ---

channel_name               Passenger Paramvir   Slayy Point
dv_virality_score                       0.416  1.599000e+00
idv1_engagement_rate                    3.086  2.917000e+00
idv2_title_sensationalism               2.575  9.250000e-01
idv3_duration_minutes                  41.280  1.746500e+01
idv4a_comment_volume                 1909.300  1.237752e+04
idv5_tag_count                         42.050  8.925000e+00
idv6_title_length                       7.300  6.850000e+00
med1_like_to_view_ratio                 2.920  2.824000e+00
mod2_upload_recency_days              117.425  5.782500e+02
cv1_subscriber_count              2640000.000  1.040000e+07
cv2_video_age_days                    117.425  5.782500e+02
views                             1098222.950  1.662624e+07
likes                               30279.650  4.198362e+05

--- VIRALITY SCORE BREAKDOWN ---

                        Mean    Median       Max       Min       Std
channel_name
Passenger Paramvir  0.415994  0.386066  1.057528  0.028236  0.204173
Slayy Point         1.598677  1.493384  4.127442  0.128418  0.739040

--- LANGUAGE DISTRIBUTION ---

cv4_language        de  en  id  no  sv
channel_name
Passenger Paramvir   1  38   1   0   0
Slayy Point          2  36   0   1   1

--- MISSING VALUES ---
No missing values.

[DONE] Part 1 Complete.
[NEXT] Run Part 2 to scrape 20 comments per video.
       Part 2 adds: idv4b_positive_ratio, idv7_reply_rate, med2_sentiment

In [14]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import time
from tqdm import tqdm
from IPython.display import display

analyzer = SentimentIntensityAnalyzer()
COMMENTS_PER_VIDEO = 20
COMMENT_VAULT_FILE = 'yt_comment_vault.csv'

print("[SUCCESS] Part 2 Imports Ready.")
print(f"Comments Per Video : {COMMENTS_PER_VIDEO}")
print(f"Total Target       : 80 videos × {COMMENTS_PER_VIDEO} = {80 * COMMENTS_PER_VIDEO} comments")
print(f"Output File        : {COMMENT_VAULT_FILE}")
print("-" * 60)

[SUCCESS] Part 2 Imports Ready.
Comments Per Video : 20
Total Target       : 80 videos × 20 = 1600 comments
Output File        : yt_comment_vault.csv
------------------------------------------------------------

In [15]:
# ==============================================================
# STEP 5: COMMENT SCRAPING FUNCTION
# Scrapes top N comments for a given video_id
# Returns list of dicts — one per comment
# ==============================================================

def scrape_comments(video_id, video_title, channel_name, max_comments=20):
    comments_data  = []
    next_page_token = None
    total_fetched   = 0

    while total_fetched < max_comments:
        remaining = max_comments - total_fetched

        try:
            response = youtube.commentThreads().list(
                part       = 'snippet',
                videoId    = video_id,
                maxResults = min(100, remaining),  # API max per page = 100
                order      = 'relevance',           # Top comments first
                pageToken  = next_page_token,
                textFormat = 'plainText'
            ).execute()

            for item in response.get('items', []):
                # Top-level comment
                top_comment   = item['snippet']['topLevelComment']['snippet']
                comment_text  = top_comment.get('textDisplay', '')
                comment_likes = int(top_comment.get('likeCount', 0))
                comment_date  = top_comment.get('publishedAt', '')
                author        = top_comment.get('authorDisplayName', '')
                reply_count   = int(item['snippet'].get('totalReplyCount', 0))

                comments_data.append({
                    'video_id'        : video_id,
                    'video_title'     : video_title,
                    'channel_name'    : channel_name,
                    'comment_text'    : comment_text,
                    'comment_likes'   : comment_likes,
                    'reply_count'     : reply_count,
                    'comment_author'  : author,
                    'comment_date'    : comment_date,
                })

                total_fetched += 1
                if total_fetched >= max_comments:
                    break

            next_page_token = response.get('nextPageToken')
            if not next_page_token:
                break

            time.sleep(0.3)

        except Exception as e:
            # Comments disabled on some videos — skip silently
            err_msg = str(e)
            if 'commentsDisabled' in err_msg or 'disabled comments' in err_msg.lower():
                print(f"      [!] Comments disabled — video: {video_id}")
            else:
                print(f"      [!] Comment fetch error on {video_id}: {e}")
            break

    return comments_data


print("[SUCCESS] scrape_comments() Function Ready.")
print("  -> Scrapes top 20 comments per video")
print("  -> Handles disabled comments gracefully")
print("  -> Returns: comment_text, likes, reply_count, author, date")

[SUCCESS] scrape_comments() Function Ready.
  -> Scrapes top 20 comments per video
  -> Handles disabled comments gracefully
  -> Returns: comment_text, likes, reply_count, author, date

In [16]:
# ==============================================================
# PHASE 4: SCRAPE 20 COMMENTS FOR ALL 80 VIDEOS
# Reads video_id and title from yt_video_vault.csv
# ==============================================================

print("\n=== PHASE 4: COMMENT SCRAPING ===")

# Load the video vault from Part 1
df_videos = pd.read_csv('yt_video_vault.csv')
print(f"Videos loaded from vault : {len(df_videos)}")
print(f"Target comments          : {len(df_videos)} × {COMMENTS_PER_VIDEO} = {len(df_videos) * COMMENTS_PER_VIDEO}\n")

all_comments = []

for channel_name in df_videos['channel_name'].unique():
    channel_videos = df_videos[df_videos['channel_name'] == channel_name].reset_index(drop=True)

    print(f"[+] Scraping comments for : {channel_name}  ({len(channel_videos)} videos)")
    print("-" * 60)

    for _, row in tqdm(channel_videos.iterrows(), total=len(channel_videos), desc=f"     {channel_name}"):
        video_id    = row['video_id']
        video_title = row['title']

        comments = scrape_comments(
            video_id    = video_id,
            video_title = video_title,
            channel_name= channel_name,
            max_comments= COMMENTS_PER_VIDEO
        )

        all_comments.extend(comments)
        time.sleep(0.5)  # Polite delay between videos

    ch_comments = len([c for c in all_comments if c['channel_name'] == channel_name])
    print(f"\n  [SUCCESS] {channel_name} : {ch_comments} comments scraped.\n")
    print("=" * 60 + "\n")

# Save raw comment vault
if len(all_comments) > 0:
    df_comments = pd.DataFrame(all_comments)
    df_comments.to_csv(COMMENT_VAULT_FILE, index=False)

    print(f"[DONE] Comment Vault Saved : {COMMENT_VAULT_FILE}")
    print(f"Total Comments Scraped     : {len(df_comments)}")
    for ch in df_comments['channel_name'].unique():
        print(f"  {ch:35s} : {len(df_comments[df_comments['channel_name']==ch])} comments")
    print(f"Videos with < {COMMENTS_PER_VIDEO} comments  : "
          f"{df_comments.groupby('video_id').size()[df_comments.groupby('video_id').size() < COMMENTS_PER_VIDEO].count()}"
          f" (comments disabled or low engagement)")
else:
    print("FATAL ERROR: No comments scraped. Check API Key.")

=== PHASE 4: COMMENT SCRAPING ===
Videos loaded from vault : 80
Target comments          : 80 × 20 = 1600

[+] Scraping comments for : Slayy Point  (40 videos)
------------------------------------------------------------

     Slayy Point: 100%|██████████| 40/40 [00:54<00:00,  1.36s/it]

  [SUCCESS] Slayy Point : 800 comments scraped.

============================================================

[+] Scraping comments for : Passenger Paramvir  (40 videos)
------------------------------------------------------------

     Passenger Paramvir: 100%|██████████| 40/40 [00:52<00:00,  1.32s/it]

  [SUCCESS] Passenger Paramvir : 800 comments scraped.

============================================================

[DONE] Comment Vault Saved : yt_comment_vault.csv
Total Comments Scraped     : 1600
  Slayy Point                         : 800 comments
  Passenger Paramvir                  : 800 comments
Videos with < 20 comments  : 0 (comments disabled or low engagement)

In [17]:
# ==============================================================
# PHASE 5: NLP — VADER SENTIMENT ON ALL COMMENTS
# Computes compound score per comment
# Then flags is_positive: 1 if compound > 0.05 else 0
# ==============================================================

print("\n=== PHASE 5: VADER SENTIMENT ANALYSIS ===")

df_comments = pd.read_csv(COMMENT_VAULT_FILE)
print(f"Comments loaded : {len(df_comments)}")

tqdm.pandas(desc="     Running VADER")

# Compound score per comment — scale: -1 (negative) to +1 (positive)
df_comments['vader_compound'] = df_comments['comment_text'].progress_apply(
    lambda text: analyzer.polarity_scores(str(text))['compound']
)

# Binary positive flag — standard VADER threshold
# > 0.05 = positive, < -0.05 = negative, in between = neutral
df_comments['is_positive'] = df_comments['vader_compound'].apply(
    lambda score: 1 if score > 0.05 else 0
)

# Save updated comment vault with sentiment
df_comments.to_csv(COMMENT_VAULT_FILE, index=False)

print(f"\n[DONE] Sentiment Added to Comment Vault.")
print(f"Total Comments    : {len(df_comments)}")
print(f"Positive Comments : {df_comments['is_positive'].sum()} ({df_comments['is_positive'].mean()*100:.1f}%)")
print(f"Non-Positive      : {(df_comments['is_positive']==0).sum()} ({(df_comments['is_positive']==0).mean()*100:.1f}%)")
print("\n--- SENTIMENT BREAKDOWN BY CHANNEL ---")
display(df_comments.groupby('channel_name')[['vader_compound','is_positive']].mean().round(3))

=== PHASE 5: VADER SENTIMENT ANALYSIS ===
Comments loaded : 1600

     Running VADER: 100%|██████████| 1600/1600 [00:00<00:00, 5331.48it/s]

[DONE] Sentiment Added to Comment Vault.
Total Comments    : 1600
Positive Comments : 1012 (63.2%)
Non-Positive      : 588 (36.8%)

--- SENTIMENT BREAKDOWN BY CHANNEL ---

                    vader_compound  is_positive
channel_name
Passenger Paramvir           0.370        0.639
Slayy Point                  0.343        0.626

In [18]:
# ==============================================================
# PHASE 6: AGGREGATE COMMENT STATS → VIDEO LEVEL
# Computes IDV4b, IDV6 (reply rate), Med2 per video
# Then merges back into yt_video_vault.csv → yt_master_vault.csv
# ==============================================================

print("\n=== PHASE 6: AGGREGATION & MERGE ===")

df_comments = pd.read_csv(COMMENT_VAULT_FILE)
df_videos   = pd.read_csv('yt_video_vault.csv')

# --- Aggregate per video_id ---
agg = df_comments.groupby('video_id').agg(
    scraped_comment_count = ('comment_text',    'count'),
    total_reply_count     = ('reply_count',      'sum'),
    positive_count        = ('is_positive',      'sum'),
    med2_comment_sentiment= ('vader_compound',   'mean'),  # Mediator 2
).reset_index()

# IDV4b — Positive Comment Ratio = positive ÷ scraped × 100
agg['idv4b_positive_comment_ratio'] = (
    agg['positive_count'] / agg['scraped_comment_count'] * 100
).round(4)

# IDV6 — Reply Engagement Rate = total replies ÷ raw total comments
# Use raw_comment_count from video vault (total comments on video)
# not just the 20 we scraped — gives more accurate ratio
agg = agg.merge(
    df_videos[['video_id', 'raw_comment_count']],
    on='video_id', how='left'
)
agg['idv6_reply_engagement_rate'] = (
    agg['total_reply_count'] / agg['raw_comment_count']
).round(6)
agg['idv6_reply_engagement_rate'] = agg['idv6_reply_engagement_rate'].fillna(0)

# Round sentiment
agg['med2_comment_sentiment'] = agg['med2_comment_sentiment'].round(4)

# Keep only the columns we need for merge
agg_final = agg[['video_id', 'scraped_comment_count',
                  'idv4b_positive_comment_ratio',
                  'idv6_reply_engagement_rate',
                  'med2_comment_sentiment']]

# --- Merge into video vault ---
df_master = df_videos.merge(agg_final, on='video_id', how='left')

# Fill any videos where comments were disabled
df_master['idv4b_positive_comment_ratio']  = df_master['idv4b_positive_comment_ratio'].fillna(0)
df_master['idv6_reply_engagement_rate']    = df_master['idv6_reply_engagement_rate'].fillna(0)
df_master['med2_comment_sentiment']        = df_master['med2_comment_sentiment'].fillna(0)
df_master['scraped_comment_count']         = df_master['scraped_comment_count'].fillna(0)

# Save master vault
MASTER_VAULT = 'yt_master_vault.csv'
df_master.to_csv(MASTER_VAULT, index=False)

print(f"[DONE] Master Vault Saved : {MASTER_VAULT}")
print(f"Total Rows                : {len(df_master)}")
print(f"Total Columns             : {len(df_master.columns)}")
print(f"\n--- NEW COLUMNS ADDED ---")
print("  idv4b_positive_comment_ratio")
print("  idv6_reply_engagement_rate")
print("  med2_comment_sentiment")
print("  scraped_comment_count")

=== PHASE 6: AGGREGATION & MERGE ===
[DONE] Master Vault Saved : yt_master_vault.csv
Total Rows                : 80
Total Columns             : 31

--- NEW COLUMNS ADDED ---
  idv4b_positive_comment_ratio
  idv6_reply_engagement_rate
  med2_comment_sentiment
  scraped_comment_count

In [21]:
# ==============================================================
# FIX: Rename columns to match final model numbering
# idv6_title_length       → idv5_title_length
# idv6_reply_engagement_rate stays as idv6
# ==============================================================

df_master = pd.read_csv('yt_master_vault.csv')

df_master = df_master.rename(columns={
    'idv6_title_length' : 'idv5_title_length'
})

df_master.to_csv('yt_master_vault.csv', index=False)

print("[DONE] Column renamed: idv6_title_length → idv5_title_length")
print("\nFinal column list:")
for i, col in enumerate(df_master.columns, 1):
    print(f"  {i:02d}. {col}")

[DONE] Column renamed: idv6_title_length → idv5_title_length

Final column list:
  01. channel_name
  02. video_id
  03. video_url
  04. title
  05. views
  06. likes
  07. raw_comment_count
  08. raw_duration_seconds
  09. raw_tag_count
  10. raw_upload_date
  11. raw_published_at
  12. dv_virality_score
  13. idv1_engagement_rate
  14. idv2_title_sensationalism
  15. idv3_duration_minutes
  16. idv4a_comment_volume
  17. idv5_tag_count
  18. idv5_title_length
  19. med1_like_to_view_ratio
  20. mod1_content_category
  21. mod1_category_code
  22. mod2_upload_recency_days
  23. cv1_subscriber_count
  24. cv2_video_age_days
  25. cv3_day_of_week
  26. cv3_day_of_week_num
  27. cv4_language
  28. scraped_comment_count
  29. idv4b_positive_comment_ratio
  30. idv6_reply_engagement_rate
  31. med2_comment_sentiment

In [22]:
# ==============================================================
# PHASE 7: MASTER VAULT — FINAL PREVIEW & HEALTH CHECK
# ==============================================================

df_master = pd.read_csv('yt_master_vault.csv')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 40)

print("=== PHASE 7: MASTER VAULT PREVIEW ===")
print(f"Rows    : {len(df_master)}")
print(f"Columns : {len(df_master.columns)}\n")

all_idvs = [
    'dv_virality_score',
    'idv1_engagement_rate',
    'idv2_title_sensationalism',
    'idv3_duration_minutes',
    'idv4a_comment_volume',
    'idv4b_positive_comment_ratio',
    'idv5_title_length',
    'idv6_reply_engagement_rate',
    'med1_like_to_view_ratio',
    'med2_comment_sentiment',
    'mod2_upload_recency_days',
    'cv1_subscriber_count',
    'cv2_video_age_days'
]

print("--- MEAN VALUES PER CHANNEL ---")
display(df_master.groupby('channel_name')[all_idvs].mean().round(3).T)

print("\n--- MISSING VALUES CHECK ---")
missing = df_master[all_idvs].isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else "  No missing values. Master vault is clean.")

print("\n[DONE] Part 2 Complete.")
print("[NEXT] Master vault is ready for Analysis — H1 to H7.")

=== PHASE 7: MASTER VAULT PREVIEW ===
Rows    : 80
Columns : 31

--- MEAN VALUES PER CHANNEL ---

channel_name                  Passenger Paramvir   Slayy Point
dv_virality_score                          0.416  1.599000e+00
idv1_engagement_rate                       3.086  2.917000e+00
idv2_title_sensationalism                  2.575  9.250000e-01
idv3_duration_minutes                     41.280  1.746500e+01
idv4a_comment_volume                    1909.300  1.237752e+04
idv4b_positive_comment_ratio              63.875  6.262500e+01
idv5_title_length                          7.300  6.850000e+00
idv6_reply_engagement_rate                 0.082  4.200000e-02
med1_like_to_view_ratio                    2.920  2.824000e+00
med2_comment_sentiment                     0.370  3.430000e-01
mod2_upload_recency_days                 117.425  5.782500e+02
cv1_subscriber_count                 2640000.000  1.040000e+07
cv2_video_age_days                       117.425  5.782500e+02

--- MISSING VALUES CHECK ---
  No missing values. Master vault is clean.

[DONE] Part 2 Complete.
[NEXT] Master vault is ready for Analysis — H1 to H7.

In [23]:
# ==============================================================
# ANALYSIS: IMPORTS & SETUP
# ==============================================================
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy import stats
from IPython.display import display

df = pd.read_csv('yt_master_vault.csv')

# Fix column names for statsmodels (no spaces, no special chars)
df.columns = [c.replace(' ', '_').replace('&', 'and').replace('-', '_') for c in df.columns]

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.4f}'.format)

def sig_stars(p):
    if p < 0.001: return '***'
    elif p < 0.01: return '**'
    elif p < 0.05: return '*'
    elif p < 0.10: return '†'
    else: return 'ns'

print("[SUCCESS] Analysis Setup Ready.")
print(f"Dataset : {len(df)} rows × {len(df.columns)} columns")
print("-" * 60)

[SUCCESS] Analysis Setup Ready.
Dataset : 80 rows × 31 columns
------------------------------------------------------------

In [24]:
# ==============================================================
# H1 & H2: DIRECT EFFECTS — ALL IDVs → VIRALITY SCORE
# OLS Regression: DV ~ IDV1 + IDV2 + IDV3 + IDV4a + IDV4b +
#                       IDV5 + IDV6
# Tests H1: Engagement Rate → Virality (+)
# Tests H2: Title Sensationalism → Virality (+)
# Other IDVs included for completeness
# ==============================================================

print("\n=== H1 & H2: DIRECT EFFECTS — ALL IDVs → VIRALITY SCORE ===\n")

formula_direct = (
    'dv_virality_score ~ '
    'idv1_engagement_rate + '
    'idv2_title_sensationalism + '
    'idv3_duration_minutes + '
    'idv4a_comment_volume + '
    'idv4b_positive_comment_ratio + '
    'idv5_title_length + '
    'idv6_reply_engagement_rate'
)

model_direct = smf.ols(formula_direct, data=df).fit()

print("--- MODEL 1: DIRECT EFFECTS (No Controls) ---")
print(f"R²        : {model_direct.rsquared:.4f}")
print(f"Adj. R²   : {model_direct.rsquared_adj:.4f}")
print(f"F-stat    : {model_direct.fvalue:.4f}  (p = {model_direct.f_pvalue:.4f})")
print(f"N         : {int(model_direct.nobs)}")
print()

results_direct = []
for var in model_direct.params.index:
    b   = model_direct.params[var]
    se  = model_direct.bse[var]
    t   = model_direct.tvalues[var]
    p   = model_direct.pvalues[var]
    results_direct.append({
        'Variable' : var,
        'β (Coef)' : round(b, 4),
        'Std Error': round(se, 4),
        't-value'  : round(t, 4),
        'p-value'  : round(p, 4),
        'Sig'      : sig_stars(p)
    })

df_direct = pd.DataFrame(results_direct)
print(df_direct.to_string(index=False))

print("\n--- HYPOTHESIS VERDICT ---")
# H1
h1_p = model_direct.pvalues['idv1_engagement_rate']
h1_b = model_direct.params['idv1_engagement_rate']
print(f"H1 — Engagement Rate → Virality       : β={h1_b:.4f}, p={h1_p:.4f} {sig_stars(h1_p)}")
print(f"     {'SUPPORTED ✅' if h1_p < 0.05 and h1_b > 0 else 'NOT SUPPORTED ❌'}")

# H2
h2_p = model_direct.pvalues['idv2_title_sensationalism']
h2_b = model_direct.params['idv2_title_sensationalism']
print(f"\nH2 — Title Sensationalism → Virality   : β={h2_b:.4f}, p={h2_p:.4f} {sig_stars(h2_p)}")
print(f"     {'SUPPORTED ✅' if h2_p < 0.05 and h2_b > 0 else 'NOT SUPPORTED ❌'}")

=== H1 & H2: DIRECT EFFECTS — ALL IDVs → VIRALITY SCORE ===

--- MODEL 1: DIRECT EFFECTS (No Controls) ---
R²        : 0.7410
Adj. R²   : 0.7158
F-stat    : 29.4222  (p = 0.0000)
N         : 80

                    Variable  β (Coef)  Std Error  t-value  p-value Sig
                   Intercept    1.6145     0.4143   3.8971   0.0002 ***
        idv1_engagement_rate   -0.3881     0.0571  -6.7979   0.0000 ***
   idv2_title_sensationalism   -0.0864     0.0407  -2.1233   0.0372   *
       idv3_duration_minutes   -0.0125     0.0036  -3.4436   0.0010 ***
        idv4a_comment_volume    0.0001     0.0000   5.8015   0.0000 ***
idv4b_positive_comment_ratio    0.0061     0.0033   1.8736   0.0650   †
           idv5_title_length    0.0455     0.0297   1.5327   0.1297  ns
  idv6_reply_engagement_rate   -0.7131     1.5099  -0.4723   0.6381  ns

--- HYPOTHESIS VERDICT ---
H1 — Engagement Rate → Virality       : β=-0.3881, p=0.0000 ***
     NOT SUPPORTED ❌

H2 — Title Sensationalism → Virality   : β=-0.0864, p=0.0372 *
     NOT SUPPORTED ❌

In [25]:
# ==============================================================
# H1 & H2 WITH CONTROL VARIABLES ADDED
# OLS: DV ~ All IDVs + C1 + C2 + C3
# This is the MAIN MODEL for H1 and H2
# Controls isolate true IDV effects from channel/video confounds
# ==============================================================

print("\n=== H1 & H2: DIRECT EFFECTS + CONTROL VARIABLES ===\n")

formula_controls = (
    'dv_virality_score ~ '
    'idv1_engagement_rate + '
    'idv2_title_sensationalism + '
    'idv3_duration_minutes + '
    'idv4a_comment_volume + '
    'idv4b_positive_comment_ratio + '
    'idv5_title_length + '
    'idv6_reply_engagement_rate + '
    'cv1_subscriber_count + '
    'cv2_video_age_days + '
    'cv3_day_of_week_num'
)

model_controls = smf.ols(formula_controls, data=df).fit()

print("--- MODEL 2: DIRECT EFFECTS + CONTROLS ---")
print(f"R²        : {model_controls.rsquared:.4f}")
print(f"Adj. R²   : {model_controls.rsquared_adj:.4f}")
print(f"F-stat    : {model_controls.fvalue:.4f}  (p = {model_controls.f_pvalue:.4f})")
print(f"N         : {int(model_controls.nobs)}")
print()

results_controls = []
for var in model_controls.params.index:
    b  = model_controls.params[var]
    se = model_controls.bse[var]
    t  = model_controls.tvalues[var]
    p  = model_controls.pvalues[var]
    results_controls.append({
        'Variable' : var,
        'β (Coef)' : round(b, 4),
        'Std Error': round(se, 4),
        't-value'  : round(t, 4),
        'p-value'  : round(p, 4),
        'Sig'      : sig_stars(p)
    })

df_controls = pd.DataFrame(results_controls)
print(df_controls.to_string(index=False))

# R² Change from Model 1 → Model 2
r2_change = model_controls.rsquared - model_direct.rsquared
print(f"\n--- MODEL COMPARISON ---")
print(f"Model 1 R² (No Controls)   : {model_direct.rsquared:.4f}")
print(f"Model 2 R² (With Controls) : {model_controls.rsquared:.4f}")
print(f"R² Change                  : +{r2_change:.4f}")

print("\n--- HYPOTHESIS VERDICT (With Controls) ---")
# H1
h1_p = model_controls.pvalues['idv1_engagement_rate']
h1_b = model_controls.params['idv1_engagement_rate']
print(f"H1 — Engagement Rate → Virality       : β={h1_b:.4f}, p={h1_p:.4f} {sig_stars(h1_p)}")
print(f"     {'SUPPORTED ✅' if h1_p < 0.05 and h1_b > 0 else 'NOT SUPPORTED ❌'}")

# H2
h2_p = model_controls.pvalues['idv2_title_sensationalism']
h2_b = model_controls.params['idv2_title_sensationalism']
print(f"\nH2 — Title Sensationalism → Virality   : β={h2_b:.4f}, p={h2_p:.4f} {sig_stars(h2_p)}")
print(f"     {'SUPPORTED ✅' if h2_p < 0.05 and h2_b > 0 else 'NOT SUPPORTED ❌'}")

# H7 — Control variables significance
print(f"\n--- H7: CONTROL VARIABLES SIGNIFICANCE ---")
for cv in ['cv1_subscriber_count', 'cv2_video_age_days', 'cv3_day_of_week_num']:
    p = model_controls.pvalues[cv]
    b = model_controls.params[cv]
    print(f"  {cv:30s} : β={b:.4f}, p={p:.4f} {sig_stars(p)}")
h7_any_sig = any(model_controls.pvalues[cv] < 0.05
                 for cv in ['cv1_subscriber_count','cv2_video_age_days','cv3_day_of_week_num'])
print(f"\nH7 — Controls affect Virality  : {'SUPPORTED ✅' if h7_any_sig else 'NOT SUPPORTED ❌'}")

=== H1 & H2: DIRECT EFFECTS + CONTROL VARIABLES ===

--- MODEL 2: DIRECT EFFECTS + CONTROLS ---
R²        : 0.8257
Adj. R²   : 0.8004
F-stat    : 32.6774  (p = 0.0000)
N         : 80

                    Variable  β (Coef)  Std Error  t-value  p-value Sig
                   Intercept    0.5146     0.4692   1.0968   0.2766  ns
        idv1_engagement_rate   -0.2396     0.0543  -4.4094   0.0000 ***
   idv2_title_sensationalism   -0.0407     0.0357  -1.1412   0.2577  ns
       idv3_duration_minutes   -0.0020     0.0040  -0.5125   0.6100  ns
        idv4a_comment_volume    0.0000     0.0000   3.1913   0.0021  **
idv4b_positive_comment_ratio   -0.0002     0.0030  -0.0805   0.9361  ns
           idv5_title_length    0.0573     0.0252   2.2699   0.0263   *
  idv6_reply_engagement_rate    1.7960     1.4550   1.2344   0.2213  ns
        cv1_subscriber_count    0.0000     0.0000   1.0850   0.2817  ns
          cv2_video_age_days    0.0011     0.0002   5.2641   0.0000 ***
         cv3_day_of_week_num   -0.0000     0.0214  -0.0021   0.9983  ns

--- MODEL COMPARISON ---
Model 1 R² (No Controls)   : 0.7410
Model 2 R² (With Controls) : 0.8257
R² Change                  : +0.0847

--- HYPOTHESIS VERDICT (With Controls) ---
H1 — Engagement Rate → Virality       : β=-0.2396, p=0.0000 ***
     NOT SUPPORTED ❌

H2 — Title Sensationalism → Virality   : β=-0.0407, p=0.2577 ns
     NOT SUPPORTED ❌

--- H7: CONTROL VARIABLES SIGNIFICANCE ---
  cv1_subscriber_count           : β=0.0000, p=0.2817 ns
  cv2_video_age_days             : β=0.0011, p=0.0000 ***
  cv3_day_of_week_num            : β=-0.0000, p=0.9983 ns

H7 — Controls affect Virality  : SUPPORTED ✅

In [26]:
# ==============================================================
# H5: MEDIATION — Like-to-View Ratio mediates Engagement → DV
# H6: MEDIATION — Comment Sentiment mediates Sensationalism → DV
# Method: SEM-style 2-model approach + Sobel Test
# Path A: IV → Mediator
# Path B: Mediator → DV (controlling for IV)
# Indirect Effect = Path A × Path B
# Sobel Z = (a*b) / sqrt(b²*sa² + a²*sb²)
# ==============================================================

print("\n=== H5 & H6: MEDIATION ANALYSIS (SOBEL TEST) ===\n")

def run_mediation(iv, mediator, dv, data, label):
    print(f"--- {label} ---")
    print(f"    IV: {iv}  |  Mediator: {mediator}  |  DV: {dv}")

    # Path A: IV → Mediator
    path_a_model = smf.ols(f'{mediator} ~ {iv}', data=data).fit()
    a    = path_a_model.params[iv]
    sa   = path_a_model.bse[iv]
    pa   = path_a_model.pvalues[iv]

    # Path B: Mediator → DV (controlling for IV)
    path_b_model = smf.ols(f'{dv} ~ {iv} + {mediator}', data=data).fit()
    b    = path_b_model.params[mediator]
    sb   = path_b_model.bse[mediator]
    pb   = path_b_model.pvalues[mediator]

    # Direct effect of IV on DV (with mediator in model)
    c_prime   = path_b_model.params[iv]
    p_cprime  = path_b_model.pvalues[iv]

    # Total effect of IV on DV (without mediator)
    total_model = smf.ols(f'{dv} ~ {iv}', data=data).fit()
    c    = total_model.params[iv]

    # Indirect effect
    indirect = a * b

    # Sobel Test
    sobel_se = np.sqrt((b**2 * sa**2) + (a**2 * sb**2))
    sobel_z  = indirect / sobel_se
    sobel_p  = 2 * (1 - stats.norm.cdf(abs(sobel_z)))

    print(f"\n  Path A  (IV → Mediator)        : a = {a:.4f},  SE = {sa:.4f},  p = {pa:.4f} {sig_stars(pa)}")
    print(f"  Path B  (Mediator → DV | IV)   : b = {b:.4f},  SE = {sb:.4f},  p = {pb:.4f} {sig_stars(pb)}")
    print(f"  Total Effect   (c)             : {c:.4f}")
    print(f"  Direct Effect  (c')            : {c_prime:.4f},  p = {p_cprime:.4f} {sig_stars(p_cprime)}")
    print(f"  Indirect Effect (a × b)        : {indirect:.4f}")
    print(f"  Sobel Z                        : {sobel_z:.4f}")
    print(f"  Sobel p-value                  : {sobel_p:.4f} {sig_stars(sobel_p)}")

    supported = sobel_p < 0.05 and pa < 0.05 and pb < 0.05
    print(f"\n  VERDICT : {'MEDIATION SUPPORTED ✅' if supported else 'MEDIATION NOT SUPPORTED ❌'}")
    if supported:
        if abs(c_prime) < abs(c) * 0.20:
            print(f"  TYPE    : Full Mediation (direct effect reduced to near zero)")
        else:
            print(f"  TYPE    : Partial Mediation (direct effect remains significant)")
    print()
    return sobel_p

# H5: Like-to-View Ratio mediates Engagement Rate → Virality
p_h5 = run_mediation(
    iv       = 'idv1_engagement_rate',
    mediator = 'med1_like_to_view_ratio',
    dv       = 'dv_virality_score',
    data     = df,
    label    = 'H5: Like-to-View Ratio mediates Engagement → Virality'
)

print("=" * 70)

# H6: Comment Sentiment mediates Title Sensationalism → Virality
p_h6 = run_mediation(
    iv       = 'idv2_title_sensationalism',
    mediator = 'med2_comment_sentiment',
    dv       = 'dv_virality_score',
    data     = df,
    label    = 'H6: Comment Sentiment mediates Sensationalism → Virality'
)

=== H5 & H6: MEDIATION ANALYSIS (SOBEL TEST) ===

--- H5: Like-to-View Ratio mediates Engagement → Virality ---
    IV: idv1_engagement_rate  |  Mediator: med1_like_to_view_ratio  |  DV: dv_virality_score

  Path A  (IV → Mediator)        : a = 0.9646,  SE = 0.0088,  p = 0.0000 ***
  Path B  (Mediator → DV | IV)   : b = 4.1732,  SE = 0.9901,  p = 0.0001 ***
  Total Effect   (c)             : -0.3644
  Direct Effect  (c')            : -4.3898,  p = 0.0000 ***
  Indirect Effect (a × b)        : 4.0254
  Sobel Z                        : 4.2120
  Sobel p-value                  : 0.0000 ***

  VERDICT : MEDIATION SUPPORTED ✅
  TYPE    : Partial Mediation (direct effect remains significant)

======================================================================
--- H6: Comment Sentiment mediates Sensationalism → Virality ---
    IV: idv2_title_sensationalism  |  Mediator: med2_comment_sentiment  |  DV: dv_virality_score

  Path A  (IV → Mediator)        : a = 0.0067,  SE = 0.0143,  p = 0.6412 ns
  Path B  (Mediator → DV | IV)   : b = 0.7298,  SE = 0.4363,  p = 0.0985 †
  Total Effect   (c)             : -0.2567
  Direct Effect  (c')            : -0.2616,  p = 0.0000 ***
  Indirect Effect (a × b)        : 0.0049
  Sobel Z                        : 0.4505
  Sobel p-value                  : 0.6523 ns

  VERDICT : MEDIATION NOT SUPPORTED ❌

In [27]:
# ==============================================================
# H3: MODERATION — Content Category moderates Sensationalism → DV
# H4: MODERATION — Upload Recency moderates Engagement → DV
# Method: Interaction term approach
# Step 1: Base model (IV + Moderator → DV)
# Step 2: Full model (IV + Moderator + IV×Moderator → DV)
# Step 3: F-test for R² change
# Step 4: Simple slopes at each level of moderator
# ==============================================================

print("\n=== H3 & H4: MODERATION ANALYSIS ===\n")

def run_moderation(iv, moderator, dv, data, label, moderator_type='continuous'):
    print(f"--- {label} ---")
    print(f"    IV: {iv}  |  Moderator: {moderator}  |  DV: {dv}\n")

    # Mean-center continuous moderator to reduce multicollinearity
    if moderator_type == 'continuous':
        data = data.copy()
        data[f'{moderator}_c'] = data[moderator] - data[moderator].mean()
        mod_term = f'{moderator}_c'
    else:
        mod_term = moderator

    interaction_term = f'{iv}_x_{mod_term}'
    data[interaction_term] = data[iv] * data[mod_term]

    # Base model — no interaction
    base_model = smf.ols(f'{dv} ~ {iv} + {mod_term}', data=data).fit()

    # Full model — with interaction
    full_model = smf.ols(f'{dv} ~ {iv} + {mod_term} + {interaction_term}', data=data).fit()

    # F-test for R² change
    r2_change   = full_model.rsquared - base_model.rsquared
    n           = len(data)
    k_full      = len(full_model.params) - 1
    f_change    = (r2_change / 1) / ((1 - full_model.rsquared) / (n - k_full - 1))
    p_f_change  = 1 - stats.f.cdf(f_change, 1, n - k_full - 1)

    print(f"  Base Model  R²  : {base_model.rsquared:.4f}")
    print(f"  Full Model  R²  : {full_model.rsquared:.4f}")
    print(f"  R² Change       : {r2_change:.4f}")
    print(f"  F Change        : {f_change:.4f}  (p = {p_f_change:.4f}) {sig_stars(p_f_change)}")

    # Interaction coefficient
    int_coef = full_model.params[interaction_term]
    int_p    = full_model.pvalues[interaction_term]
    int_se   = full_model.bse[interaction_term]
    print(f"\n  Interaction β   : {int_coef:.4f}")
    print(f"  Interaction SE  : {int_se:.4f}")
    print(f"  Interaction p   : {int_p:.4f} {sig_stars(int_p)}")

    # Simple slopes
    print(f"\n  --- Simple Slopes ---")
    if moderator_type == 'continuous':
        for label_s, val in [('Low  (−1 SD)', -data[f'{moderator}_c'].std()),
                              ('Mean (0)',      0),
                              ('High (+1 SD)', +data[f'{moderator}_c'].std())]:
            slope = full_model.params[iv] + int_coef * val
            print(f"    {label_s} : slope = {slope:.4f}")
    else:
        for val, label_s in [(0, 'Roast (0)'), (1, 'Travel Vlog (1)')]:
            slope = full_model.params[iv] + int_coef * val
            print(f"    {label_s:20s} : slope = {slope:.4f}")

    supported = int_p < 0.05
    print(f"\n  VERDICT : {'MODERATION SUPPORTED ✅' if supported else 'MODERATION NOT SUPPORTED ❌'}")
    print()
    return int_p


# H3: Content Category moderates Title Sensationalism → Virality
p_h3 = run_moderation(
    iv             = 'idv2_title_sensationalism',
    moderator      = 'mod1_category_code',
    dv             = 'dv_virality_score',
    data           = df,
    label          = 'H3: Content Category moderates Sensationalism → Virality',
    moderator_type = 'categorical'
)

print("=" * 70 + "\n")

# H4: Upload Recency moderates Engagement Rate → Virality
p_h4 = run_moderation(
    iv             = 'idv1_engagement_rate',
    moderator      = 'mod2_upload_recency_days',
    dv             = 'dv_virality_score',
    data           = df,
    label          = 'H4: Upload Recency moderates Engagement → Virality',
    moderator_type = 'continuous'
)

=== H3 & H4: MODERATION ANALYSIS ===

--- H3: Content Category moderates Sensationalism → Virality ---
    IV: idv2_title_sensationalism  |  Moderator: mod1_category_code  |  DV: dv_virality_score

  Base Model  R²  : 0.5516
  Full Model  R²  : 0.5644
  R² Change       : 0.0129
  F Change        : 2.2442  (p = 0.1383) ns

  Interaction β   : 0.1717
  Interaction SE  : 0.1146
  Interaction p   : 0.1383 ns

  --- Simple Slopes ---
    Roast (0)            : slope = -0.1540
    Travel Vlog (1)      : slope = 0.0177

  VERDICT : MODERATION NOT SUPPORTED ❌

======================================================================

--- H4: Upload Recency moderates Engagement → Virality ---
    IV: idv1_engagement_rate  |  Moderator: mod2_upload_recency_days  |  DV: dv_virality_score

  Base Model  R²  : 0.7010
  Full Model  R²  : 0.7901
  R² Change       : 0.0891
  F Change        : 32.2685  (p = 0.0000) ***

  Interaction β   : -0.0010
  Interaction SE  : 0.0002
  Interaction p   : 0.0000 ***

  --- Simple Slopes ---
    Low  (−1 SD) : slope = -0.0146
    Mean (0) : slope = -0.3425
    High (+1 SD) : slope = -0.6703

  VERDICT : MODERATION SUPPORTED ✅

In [28]:
# ==============================================================
# FINAL SUMMARY — ALL HYPOTHESES H1 TO H7
# ==============================================================

print("\n" + "=" * 70)
print("       FINAL HYPOTHESIS SUMMARY — YouTube Virality Study")
print("=" * 70)

summary = [
    ("H1", "Engagement Rate → Virality (+)",
     model_controls.params['idv1_engagement_rate'],
     model_controls.pvalues['idv1_engagement_rate']),

    ("H2", "Title Sensationalism → Virality (+)",
     model_controls.params['idv2_title_sensationalism'],
     model_controls.pvalues['idv2_title_sensationalism']),

    ("H3", "Category moderates Sensationalism → Virality",
     None, p_h3),

    ("H4", "Upload Recency moderates Engagement → Virality",
     None, p_h4),

    ("H5", "Like-to-View mediates Engagement → Virality",
     None, p_h5),

    ("H6", "Comment Sentiment mediates Sensationalism → Virality",
     None, p_h6),

    ("H7", "Controls (C1,C2,C3) affect Virality",
     None,
     min(model_controls.pvalues['cv1_subscriber_count'],
         model_controls.pvalues['cv2_video_age_days'],
         model_controls.pvalues['cv3_day_of_week_num'])),
]

print(f"\n{'Hyp':<5} {'Description':<48} {'β':>8} {'p-value':>9} {'Sig':>5} {'Verdict'}")
print("-" * 90)

for hyp, desc, beta, p in summary:
    beta_str   = f"{beta:.4f}" if beta is not None else "   —  "
    verdict    = "Supported ✅" if p < 0.05 else "Not Supported ❌"
    print(f"{hyp:<5} {desc:<48} {beta_str:>8} {p:>9.4f} {sig_stars(p):>5}   {verdict}")

print("-" * 90)
print("Significance: *** p<0.001  ** p<0.01  * p<0.05  † p<0.10  ns = not significant")
print(f"\nMain Model R²       : {model_controls.rsquared:.4f}")
print(f"Main Model Adj. R²  : {model_controls.rsquared_adj:.4f}")
print(f"Sample Size         : {len(df)} videos (40 per channel)")
print("=" * 70)

======================================================================
       FINAL HYPOTHESIS SUMMARY — YouTube Virality Study
======================================================================

Hyp   Description                                             β   p-value   Sig Verdict
------------------------------------------------------------------------------------------
H1    Engagement Rate → Virality (+)                    -0.2396    0.0000   ***   Supported ✅
H2    Title Sensationalism → Virality (+)               -0.0407    0.2577    ns   Not Supported ❌
H3    Category moderates Sensationalism → Virality          —      0.1383    ns   Not Supported ❌
H4    Upload Recency moderates Engagement → Virality        —      0.0000   ***   Supported ✅
H5    Like-to-View mediates Engagement → Virality           —      0.0000   ***   Supported ✅
H6    Comment Sentiment mediates Sensationalism → Virality      —      0.6523    ns   Not Supported ❌
H7    Controls (C1,C2,C3) affect Virality                   —      0.0000   ***   Supported ✅
------------------------------------------------------------------------------------------
Significance: *** p<0.001  ** p<0.01  * p<0.05  † p<0.10  ns = not significant

Main Model R²       : 0.8257
Main Model Adj. R²  : 0.8004
Sample Size         : 80 videos (40 per channel)
======================================================================

In [29]:
# ==============================================================
# CORRELATION MATRIX — All Key Variables
# Pearson correlations with significance stars
# ==============================================================

print("\n=== CORRELATION MATRIX ===\n")

corr_cols = {
    'dv_virality_score'           : 'DV',
    'idv1_engagement_rate'        : 'IDV1',
    'idv2_title_sensationalism'   : 'IDV2',
    'idv3_duration_minutes'       : 'IDV3',
    'idv4a_comment_volume'        : 'IDV4a',
    'idv4b_positive_comment_ratio': 'IDV4b',
    'idv5_title_length'           : 'IDV5',
    'idv6_reply_engagement_rate'  : 'IDV6',
    'med1_like_to_view_ratio'     : 'Med1',
    'med2_comment_sentiment'      : 'Med2',
    'mod1_category_code'          : 'M1',
    'mod2_upload_recency_days'    : 'M2',
    'cv1_subscriber_count'        : 'C1',
    'cv2_video_age_days'          : 'C2',
    'cv3_day_of_week_num'         : 'C3',
}

df_corr = df[list(corr_cols.keys())].rename(columns=corr_cols)
n        = len(df_corr)
corr_mat = df_corr.corr().round(3)

# Build significance-starred correlation matrix
def corr_with_stars(df_in):
    cols   = df_in.columns
    result = pd.DataFrame(index=cols, columns=cols, dtype=object)
    for c1 in cols:
        for c2 in cols:
            if c1 == c2:
                result.loc[c1, c2] = '—'
            else:
                r, p = stats.pearsonr(df_in[c1], df_in[c2])
                stars = sig_stars(p)
                result.loc[c1, c2] = f"{r:.2f}{stars}"
    return result

corr_starred = corr_with_stars(df_corr)

print("Note: *** p<0.001  ** p<0.01  * p<0.05  † p<0.10  ns = not significant")
print("      Values show Pearson r with significance stars\n")
display(corr_starred)

print("\n--- TOP CORRELATIONS WITH VIRALITY SCORE (DV) ---")
dv_corr = []
for col in df_corr.columns:
    if col == 'DV':
        continue
    r, p = stats.pearsonr(df_corr['DV'], df_corr[col])
    dv_corr.append({
        'Variable'  : col,
        'Pearson r' : round(r, 4),
        'p-value'   : round(p, 4),
        'Sig'       : sig_stars(p),
        'Direction' : 'Positive' if r > 0 else 'Negative'
    })

df_dv_corr = pd.DataFrame(dv_corr).sort_values('Pearson r', key=abs, ascending=False)
print(df_dv_corr.to_string(index=False))

print("\n--- MULTICOLLINEARITY CHECK (High correlations among IDVs > 0.70) ---")
idv_cols = ['IDV1','IDV2','IDV3','IDV4a','IDV4b','IDV5','IDV6']
high_corr_found = False
for i, c1 in enumerate(idv_cols):
    for c2 in idv_cols[i+1:]:
        r, p = stats.pearsonr(df_corr[c1], df_corr[c2])
        if abs(r) > 0.70:
            print(f"  ⚠️  {c1} ↔ {c2} : r = {r:.3f} — HIGH multicollinearity risk")
            high_corr_found = True
if not high_corr_found:
    print("  No multicollinearity issues found (all IDV pairs r < 0.70) ✅")

=== CORRELATION MATRIX ===

Note: *** p<0.001  ** p<0.01  * p<0.05  † p<0.10  ns = not significant
      Values show Pearson r with significance stars

,DV,IDV1,IDV2,IDV3,IDV4a,IDV4b,IDV5,IDV6,Med1,Med2,M1,M2,C1,C2,C3
DV,—,-0.44***,-0.46***,-0.42***,0.68***,0.14ns,-0.02ns,-0.44***,-0.41***,0.14ns,-0.74***,0.82***,0.74***,0.82***,-0.15ns
IDV1,-0.44***,—,-0.04ns,-0.29**,-0.04ns,-0.23*,-0.02ns,0.29**,1.00***,-0.20†,0.09ns,-0.35**,-0.09ns,-0.35**,0.06ns
IDV2,-0.46***,-0.04ns,—,0.50***,-0.45***,0.06ns,0.23*,0.20†,-0.06ns,0.05ns,0.57***,-0.45***,-0.57***,-0.45***,0.12ns
IDV3,-0.42***,-0.29**,0.50***,—,-0.48***,0.05ns,0.23*,0.09ns,-0.34**,0.03ns,0.67***,-0.47***,-0.67***,-0.47***,0.04ns
IDV4a,0.68***,-0.04ns,-0.45***,-0.48***,—,-0.14ns,-0.07ns,-0.44***,-0.03ns,-0.17ns,-0.81***,0.55***,0.81***,0.55***,-0.10ns
IDV4b,0.14ns,-0.23*,0.06ns,0.05ns,-0.14ns,—,0.04ns,-0.07ns,-0.21†,0.92***,0.04ns,0.28*,-0.04ns,0.28*,0.04ns
IDV5,-0.02ns,-0.02ns,0.23*,0.23*,-0.07ns,0.04ns,—,-0.02ns,-0.03ns,0.08ns,0.13ns,-0.17ns,-0.13ns,-0.17ns,-0.10ns
IDV6,-0.44***,0.29**,0.20†,0.09ns,-0.44***,-0.07ns,-0.02ns,—,0.29**,-0.09ns,0.53***,-0.46***,-0.53***,-0.46***,-0.00ns
Med1,-0.41***,1.00***,-0.06ns,-0.34**,-0.03ns,-0.21†,-0.03ns,0.29**,—,-0.18ns,0.05ns,-0.32**,-0.05ns,-0.32**,0.05ns
Med2,0.14ns,-0.20†,0.05ns,0.03ns,-0.17ns,0.92***,0.08ns,-0.09ns,-0.18ns,—,0.07ns,0.31**,-0.07ns,0.31**,0.10ns
M1,-0.74***,0.09ns,0.57***,0.67***,-0.81***,0.04ns,0.13ns,0.53***,0.05ns,0.07ns,—,-0.70***,-1.00***,-0.70***,0.15ns
M2,0.82***,-0.35**,-0.45***,-0.47***,0.55***,0.28*,-0.17ns,-0.46***,-0.32**,0.31**,-0.70***,—,0.70***,1.00***,-0.14ns
C1,0.74***,-0.09ns,-0.57***,-0.67***,0.81***,-0.04ns,-0.13ns,-0.53***,-0.05ns,-0.07ns,-1.00***,0.70***,—,0.70***,-0.15ns
C2,0.82***,-0.35**,-0.45***,-0.47***,0.55***,0.28*,-0.17ns,-0.46***,-0.32**,0.31**,-0.70***,1.00***,0.70***,—,-0.14ns
C3,-0.15ns,0.06ns,0.12ns,0.04ns,-0.10ns,0.04ns,-0.10ns,-0.00ns,0.05ns,0.10ns,0.15ns,-0.14ns,-0.15ns,-0.14ns,—

--- TOP CORRELATIONS WITH VIRALITY SCORE (DV) ---
Variable  Pearson r  p-value Sig Direction
      M2     0.8220   0.0000 ***  Positive
      C2     0.8220   0.0000 ***  Positive
      C1     0.7413   0.0000 ***  Positive
      M1    -0.7413   0.0000 ***  Negative
   IDV4a     0.6806   0.0000 ***  Positive
    IDV2    -0.4622   0.0000 ***  Negative
    IDV6    -0.4406   0.0000 ***  Negative
    IDV1    -0.4385   0.0000 ***  Negative
    IDV3    -0.4210   0.0001 ***  Negative
    Med1    -0.4060   0.0002 ***  Negative
      C3    -0.1544   0.1715  ns  Negative
    Med2     0.1414   0.2111  ns  Positive
   IDV4b     0.1384   0.2207  ns  Positive
    IDV5    -0.0188   0.8684  ns  Negative

--- MULTICOLLINEARITY CHECK (High correlations among IDVs > 0.70) ---
  No multicollinearity issues found (all IDV pairs r < 0.70) ✅